services:
  app:
    build: .
    container_name: brutus-api-precio
    restart: always
    env_file:
      - .env
    networks:
      - web
    ports:
      - 3004:8000

networks:
  web:
    external: true